import type { Metadata } from "next";
import { Montserrat, Poppins } from "next/font/google";
import localFont from "next/font/local";
import "./base.css";
import Carousels from "@/components/Carousels";
import WidgetInteractions from "@/components/WidgetInteractions";
import JotformResizer from "@/components/JotformResizer";
import Script from "next/script";
import DeferredStylesheet from "@/components/DeferredStylesheet";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import MobileMenu from "@/components/MobileMenu";

export const metadata: Metadata = {
  title: "dbh-test",
  description: "Generated by Builder",
};

// Body fonts self-hosted via next/font (no external request, no render-blocking, auto-preloaded).
// Exposed as CSS variables that the Elementor stylesheets reference — see base.css / *.css.
const montserrat = Montserrat({
  subsets: ["latin"],
  style: ["normal", "italic"],
  display: "swap",
  variable: "--font-montserrat",
});
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
  variable: "--font-poppins",
});
// Heading font (Avenir Next LT Pro), self-hosted + preloaded via next/font/local. The single
// Black face covers the 400–900 range, matching the site's original @font-face behavior.
const avenir = localFont({
  src: "../../public/fonts/AvenirLTProBlack.ttf",
  weight: "400 900",
  style: "normal",
  display: "swap",
  variable: "--font-avenir",
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${montserrat.variable} ${poppins.variable} ${avenir.variable}`}>
      <head>
      <noscript>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css?ver=7.0.1" />
        <link rel="stylesheet" href="https://cdn.trustindex.io/assets/widget-presetted-css/v2/80-light-background.css" />
      </noscript>
      </head>
      <body className="elementor-default elementor-page-0">
        <DeferredStylesheet href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css?ver=7.0.1" />
        <DeferredStylesheet href="https://cdn.trustindex.io/assets/widget-presetted-css/v2/80-light-background.css" />
        <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-MGF7WNCV" height="0" width="0" style={{display:"none",visibility:"hidden"}} /></noscript>
        <Header />
        <MobileMenu />
        <main>{children}</main>
        <Footer />
        <WidgetInteractions />
        <Carousels />
        <JotformResizer />
        <Script id="third-party-loader" strategy="afterInteractive" dangerouslySetInnerHTML={{ __html: `(function(){var L=false;function go(){if(L)return;L=true;(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src='https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);})(window,document,'script','dataLayer','GTM-MGF7WNCV');(function () {
var a = document.createElement("script");
var b = document.getElementsByTagName("script")[0];
a.type = "text/javascript";
a.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + "js.talkfurther.com/talkfurther_init.min.js";
a.async = true;
b.parentNode.insertBefore(a, b);
})();}var E=['scroll','click','touchstart','keydown','pointerdown'];function H(){go();for(var k=0;k<E.length;k++)removeEventListener(E[k],H);}for(var k=0;k<E.length;k++)addEventListener(E[k],H,{passive:true,once:true});}());` }} />
        <Script id="body-style-guard" strategy="afterInteractive" dangerouslySetInnerHTML={{ __html: `(function(){var i=false;['click','touchstart','keydown'].forEach(function(e){document.addEventListener(e,function(){i=true;},{once:true,capture:true});});var o=new MutationObserver(function(){if(i)return;if(document.body.style.overflow==='hidden')document.body.style.overflow='';if(document.body.style.touchAction==='none')document.body.style.touchAction='';});o.observe(document.body,{attributes:true,attributeFilter:['style']});}());` }} />
      </body>
    </html>
  );
}
